### ISSUE TITLE
Allow collections to include existing datasets in remote hosts into the main catalog

### ISSUE THREAD

**Issue by zequihg50** [SantanderMetGroup/ansible-thredds-cluster#10]
```yaml
collections:
  - &collection1
    name: collection1
    path: collection1 # Id of the collection and logical path in THREDDS
    catalogs: /data/collection1
    services: [catalog, fileServer, dodsC]
    datasets:
      - content: |
           <datasetScan name="NCEP Data" path="ncep" location="/data/ldm/pub/native/grid/NCEP/">
             <metadata inherited="true">
               <serviceName>fileserver</serviceName>
               <authority>meteo.unican.es</authority>
               <dataType>Grid</dataType>
             </metadata>
           </datasetScan> 
```

The `content` of every dataset will be rendered into the main catalog of the collection, before the `</catalog>` tag.
