### ISSUE TITLE
Allow collections to be accessed through multiple paths

### ISSUE THREAD

**Issue by zequihg50** [SantanderMetGroup/ansible-thredds-cluster#11]
This would allow catalog tree hierarchies to define multiple `<datasetRoot>`. Actually they are restricted to one. This requires to add the appropriate entries in the corresponding gateways.

```yaml
collections:
  - &collection1
    name: collection1
    path: [path1,path2,path3]
    catalogs: data/collection1
    services: [catalog, fileServer, dodsC]
```
