### ISSUE TITLE
ip_address of tomcat_instances vars should be replaced with ansible host ip

### ISSUE THREAD

**Issue by zequihg50** [SantanderMetGroup/ansible-thredds-cluster#4]
The following configuration shows an example of a deployment of two hosts that should be implemented in two different plays since the ip_address couples the play to the host being deployed by Ansible. It should be replaced by the ip used by Ansible to allow identical hosts to be deployed in the same play.

```
- name: Deploy worker1
  hosts: worker1
  vars_files: 
    - workers-secret.yml
  vars:
    tomcat_install_from_source: true
    tomcat_system: false
    proxyPort: 8008
    tomcat_instances:
      - name: worker1_1800 -> dynamic ({{ whatever }})
        base_port: 1800
        ip_address: 192.168.50.12 -> dynamic ({{ whatever }})
        gws_instance: 
          - name: "{{ gws.0.name }}"
    gws:
      - name: gws1
        path: gws1/test
        location: "/group_workspaces/jasmin/gws1"

  roles:
    - role: tds 

- name: Deploy worker2
  hosts: worker2
  vars_files:
    - workers-secret.yml
  vars:
    tomcat_install_from_source: true
    tomcat_system: false
    proxyPort: 8008
    tomcat_instances:
      - name: worker1_1800
        base_port: 1800
        ip_address: 192.168.50.13
        gws_instance: 
          - name: "{{ gws.0.name }}"
    gws:
      - name: gws1
        path: gws1/test
        location: "/group_workspaces/jasmin/gws1"
  roles:
    - role: tds 
```
