### ISSUE TITLE
Change ajp field from tomcat_instances to connectors

### ISSUE THREAD

**Issue by zequihg50** [SantanderMetGroup/ansible-thredds-cluster#5]
```
  - name: Deploy tds
    hosts: tds4gws
    vars_files: 
      - tds4gws-secret.yml
    vars:
      tomcat_instances:
        - name: tds4gws_1800
          base_port: 1800
          ajp: 
            port: 18009
            proxyPort: 8008
            proxyName: 192.168.33.12
          gws_instance: 
            - name: "{{ gws.0.name }}"
```
should be:
```
  - name: Deploy tds
    hosts: tds4gws
    vars_files: 
      - tds4gws-secret.yml
    vars:
      tomcat_instances:
        - name: tds4gws_1800
          base_port: 1800
          shutdown: ...
          connectors:
            - type: ajp # mandatory
              port: 18009
              proxyPort: 8008
              proxyName: 192.168.33.12
            - type: http
              port: ...
              proxyPort: ...
              proxyName: hostname/ip or ip only? -> hostname, use it in httpd <VirtualHost>
          gws_instance: 
            - name: "{{ gws.0.name }}"
```
