### ISSUE TITLE
Allow deployment model to reference tds_instances and collections using their name

### ISSUE THREAD

**Issue by zequihg50** [SantanderMetGroup/ansible-thredds-cluster#8]
Currently we use YAML anchors to reference tds_instances and collections in the `replicas` dict of the deployment model. This requires collections and tds_instances dicts to be defined in the same yaml file where replicas are defined. This is unwanted behavior since there are scenarios where all the hosts share the same collections but the `replicas` dict differ and this force us to copy the collections dict in both yaml files.

Example:

```yaml
tomcat_base: '/usr/local'

collections:
  - &collection1
    name: collection1
    path: collection1
    catalogs:
      src: catalogs/collection1
    services: [dodsC, fileServer, catalog]

  - &collection2
    name: collection2
    path: collection2
    catalogs:
      src: catalogs/collection2
    services: [dodsC, fileServer, catalog]

tds:
  - &tomcat
    name: tomcat
    tds_content_root: /esg/content

replicas:
  - gateway: esgf
    host: "{{ ansible_eth1.ipv4.address }}"
    route: "{{ ansible_nodename }}"
    port: 8223
    tds_instance: *tomcat
    collection: *collection1
```

```yaml
tds_version: 5.0.0

collections:
  - &collection1
    name: collection1
    path: collection1
    catalogs:
      src: catalogs/collection1
    services: [dodsC, fileServer, catalog]

  - &collection2
    name: collection2
    path: collection2
    catalogs:
      src: catalogs/collection2
    services: [dodsC, fileServer, catalog]

tds:
  - &backend_instance
    name: instance1
    connectors:
      - port: 8223
        protocol: AJP/1.3

replicas:
  - gateway: esgf
    host: "{{ ansible_eth1.ipv4.address }}"
    port: 8223
    route: "{{ ansible_nodename }}"
    tds_instance: *backend_instance
    collection: *collection1

  - gateway: esgf
    host: "{{ ansible_eth1.ipv4.address }}"
    port: 8223
    route: "{{ ansible_nodename }}"
    tds_instance: *backend_instance
    collection: *collection2
```

Ideal behavior would be to refer to the `tds_instance` and `collection` using their name. However this requires, to all the tasks that loop over the replicas, to discover the appropriate dict using the `name` key and its value, e.g.

```yaml
- name: Create directories for collections in instances 
  file:
    dest: "{{ instance.tds_content_root | default(tomcat_base ~ '/' ~ instance.name ~ '/content') }}/thredds/{{ collection.path }}"
    state: directory
  with_items: "{{ replicas }}"
  vars:
    collection: "{{ collections | selectattr('name', 'equalto', 'collection1') | first }}"
    instance: "{{ tds | selectattr('name', 'equalto', 'instance1') | first }}"
```
